<a href="https://colab.research.google.com/github/Malinowsk/Ejercicios-en-Python/blob/main/creando_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Importando librerías

In [1]:
import numpy as np

### Arange

In [ ]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### Zeros

In [ ]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Ones

In [ ]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Linspace

In [ ]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

### Eye

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random

In [ ]:
np.random.rand()

0.6486667014871921

In [ ]:
np.random.rand(4)

array([0.79302843, 0.75369059, 0.14238982, 0.72556455])

In [ ]:
np.random.rand(4,4)

array([[0.59681956, 0.85704713, 0.91034912, 0.46748656],
       [0.32637472, 0.84790698, 0.12117489, 0.74476498],
       [0.58629941, 0.966222  , 0.59799968, 0.51571391],
       [0.97266925, 0.95304264, 0.65971967, 0.12739407]])

In [ ]:
np.random.randint(1,15)

13

In [ ]:
np.random.randint(1,100,(10,10))

array([[23, 79, 60, 13, 35, 57, 29, 41, 36, 76],
       [72, 99, 16, 20, 52, 15, 96, 94, 38, 77],
       [25, 97, 67, 17, 15, 27, 85, 27, 40, 79],
       [98, 69, 52, 95, 68, 55, 75, 30, 96, 37],
       [76, 26, 26, 44,  4, 20, 48, 93, 65, 58],
       [47, 51, 85, 50, 28, 16, 87, 21, 22, 47],
       [87, 85, 51, 80, 17, 67, 64, 51, 95,  5],
       [55, 57, 98,  5, 42, 61, 93, 39,  1, 50],
       [12,  7, 52, 99, 61, 37, 62, 34, 54, 31],
       [69, 58, 52, 84,  4, 41, 10, 92, 82, 10]])