<a href="https://colab.research.google.com/github/Malinowsk/Ejercicios-en-Python/blob/main/dimensiones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Importar librería

In [ ]:
import numpy as np

## Definiendo arrays

In [ ]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

In [ ]:
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [ ]:
matriz = np.array([[1,2,3],[4,5,6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

In [ ]:
tensor = np.array([[[1,2,3],[4,5,6],[7,8,9],[0,2,45]],[[1,2,3],[4,5,6],[7,8,9],[0,2,45]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 0  2 45]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 0  2 45]]]


3

## Agregar o eliminar dimensiones

In [ ]:
vector = np.array([1,2,3],ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [ ]:
expand = np.expand_dims(np.array([1,2,3]),axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [ ]:
print(vector, vector.ndim)
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)


[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1
